language: node_js
node_js:
  - 0.10

env:
  global:
    - BENCHMARK_ENDPOINT_URL=https://glowing-fire-326.firebaseio.com:443
  matrix:
    - JOB=unit-stable
    - JOB=unit-dev

before_script:
  - ./scripts/travis/setup.sh

script:
  - ./scripts/travis/build.sh
  - ./scripts/travis/benchmark.sh
